### ISSUE TITLE
no visible @interface for 'WKWebView' declares the selector 'setInspectable:'

### ISSUE THREAD

**Issue by frabarbo** [GleapSDK/Gleap-iOS-SDK#6]
on Gleap 13.2.1

Compiling GleapFrameManagerViewController.m
INFO [2024-02-06 12:40:14.43]: ▸ ❌  /Users/<name>/Library/Developer/Xcode/DerivedData/<project>/SourcePackages/checkouts/Gleap-iOS-SDK/Sources/ObjCSources/GleapFrameManagerViewController.m:432:23: no visible @interface for 'WKWebView' declares the selector 'setInspectable:'
INFO [2024-02-06 12:40:14.43]: ▸ [self.webView setInspectable: YES];

**Comment by boehlerlukas** [comment]
Hey @frabarbo !

Thanks for sharing. The method was wrapped inside an @available block, so it should work on newer XCode version. As the method isn't wanted / needed we just removed it anyways :)

v13.2.2 contains the fix for this. It might take up to 30 minutes until v13.2.2 is globally available.

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  Gleap (13.2.2) successfully published
 📅  February 6th, 14:54
 🌎  https://cocoapods.org/pods/Gleap
 👍  Tell your friends!
--------------------------------------------------------------------------------
